### ISSUE TITLE
[render] gas compression station

### ISSUE THREAD

**Issue by cascafico** [openinframap/openinframap#145]
In these days russian gas blockade and related issues are in the news. AFAIK there is no rendering for
landuse=industrial
industrail=gas

https://www.openstreetmap.org/way/263491005
https://openinframap.org/#16.43/46.503678/13.415469

Is there any tag I miss for rendering such compression station?
![compression_station](https://user-images.githubusercontent.com/6792869/165559135-5e7f7e08-69d5-4e05-be9e-65731ce244c1.png)

**Comment by russss** [comment]
There is! You have to enable the "oil and gas" layer: https://openinframap.org/#16.43/46.503678/13.415469/L,O,P

**Comment by MikiDi** [comment]
Hi @russss ,
Although it isn't the case for this particular substation, it should be noted that there are compression substations that don't show up because they don't have a [industrial=gas](https://wiki.openstreetmap.org/wiki/Key:industrial) tag associated with them ([I hope this is a correct conclusion](https://github.com/openinframap/openinframap/blob/2a9763a76514a2a406b94781e7d986145d1312b3/mapping/petroleum.py#L31) ). When looking at [these](https://wiki.openstreetmap.org/wiki/Tag:pipeline%3Dsubstation) `pipeline=substation` tagging-examples on the wiki, it isn't surprising that there are [compression substations that don't have this tag](https://overpass-turbo.eu/s/1i1d) (not to mention substations in general), i.e. the wiki doesn't suggest it in the obvious place. It would probably be good that we seek some some clarification on the tagging mailing-list regarding the wiki regardless, but do you think this could potentially justify some changes to openinframap?
Thanks in advance for your feedback!
Michaël

**Comment by russss** [comment]
Yeah, that's issue #45, which I have unfortunately had some problems implementing due to the way the pipeline tagging schema works.

**Comment by MikiDi** [comment]
Thanks! Could you elaborate on that (in the other thread would be fine)? The most obvious pipeline tagging shortcoming that I see in practice is that there is no distinction between streetside minor distribution substations and industrial ones (like there is now for electricity). Apart from that I would think openinframap is adaptable?

**Comment by flacombe** [comment]
> The most obvious pipeline tagging shortcoming that I see in practice is that there is no distinction between streetside minor distribution substations and industrial ones (like there is now for electricity).

Actually some common roles are available with substation=*, both for power and oil&gas.
https://wiki.openstreetmap.org/wiki/Key:substation

This proposal may catch your attention
https://wiki.openstreetmap.org/wiki/Proposed_features/Pipeline_substations

Let's discuss on wiki if you mind.
